//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowCtl {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlowCtl.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication required. Please log in first, then try again. Use login -h for more info..
        /// </summary>
        internal static string AuthenticationExtensions_AuthenticationIsRequired {
            get {
                return ResourceManager.GetString("AuthenticationExtensions_AuthenticationIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run the console in the background.
        /// </summary>
        internal static string Command_Console_BackgroundOption {
            get {
                return ResourceManager.GetString("Command_Console_BackgroundOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlowSynx Console is not installed. Please run the &apos;synx init -h&apos; command to see the details..
        /// </summary>
        internal static string Command_Console_ConsleIsNotInstalled {
            get {
                return ResourceManager.GetString("Command_Console_ConsleIsNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run and execute the FlowSynx console.
        /// </summary>
        internal static string Command_Console_Description {
            get {
                return ResourceManager.GetString("Command_Console_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display the version for FlowSynx Console.
        /// </summary>
        internal static string Command_ConsoleVersion_Description {
            get {
                return ResourceManager.GetString("Command_ConsoleVersion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run the FlowSynx system in the background.
        /// </summary>
        internal static string Command_Run_BackgroundOption {
            get {
                return ResourceManager.GetString("Command_Run_BackgroundOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided definition file &apos;{0}&apos; does not exist or could not be located..
        /// </summary>
        internal static string Command_Workflow_AddCommand_FileNotExist {
            get {
                return ResourceManager.GetString("Command_Workflow_AddCommand_FileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided data file &apos;{0}&apos; does not exist or could not be located..
        /// </summary>
        internal static string Command_Workflow_Triggers_AddCommand_FileNotExist {
            get {
                return ResourceManager.GetString("Command_Workflow_Triggers_AddCommand_FileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided data file &apos;{0}&apos; does not exist or could not be located..
        /// </summary>
        internal static string Command_Workflow_Triggers_UpdateCommand_FileNotExist {
            get {
                return ResourceManager.GetString("Command_Workflow_Triggers_UpdateCommand_FileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided definition file &apos;{0}&apos; does not exist or could not be located..
        /// </summary>
        internal static string Command_Workflow_UpdateCommand_FileNotExist {
            get {
                return ResourceManager.GetString("Command_Workflow_UpdateCommand_FileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A JSON-serialized data.
        /// </summary>
        internal static string Commands_AddConfig_Data {
            get {
                return ResourceManager.GetString("Commands_AddConfig_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file containing JSON-serialized data.
        /// </summary>
        internal static string Commands_AddConfig_DataFile {
            get {
                return ResourceManager.GetString("Commands_AddConfig_DataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified data file &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string Commands_AddConfig_DataFileDoesNotExist {
            get {
                return ResourceManager.GetString("Commands_AddConfig_DataFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add plugin configuration.
        /// </summary>
        internal static string Commands_AddConfig_Description {
            get {
                return ResourceManager.GetString("Commands_AddConfig_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage and display the list and details of plugin configuration.
        /// </summary>
        internal static string Commands_Config_Description {
            get {
                return ResourceManager.GetString("Commands_Config_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete plugin configuration.
        /// </summary>
        internal static string Commands_DeleteConfig_Description {
            get {
                return ResourceManager.GetString("Commands_DeleteConfig_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin config identity.
        /// </summary>
        internal static string Commands_DeleteConfig_IdentityOption {
            get {
                return ResourceManager.GetString("Commands_DeleteConfig_IdentityOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get details about plugin configuration.
        /// </summary>
        internal static string Commands_DetailsConfig_Description {
            get {
                return ResourceManager.GetString("Commands_DetailsConfig_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin config identity.
        /// </summary>
        internal static string Commands_DetailsConfig_IdentityOption {
            get {
                return ResourceManager.GetString("Commands_DetailsConfig_IdentityOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during the processing of the request..
        /// </summary>
        internal static string Commands_Error_DuringProcessingRequest {
            get {
                return ResourceManager.GetString("Commands_Error_DuringProcessingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address that specifies the HTTP endpoint used to connect to the flowsynx system.
        /// </summary>
        internal static string Commands_FlowSynxAddress {
            get {
                return ResourceManager.GetString("Commands_FlowSynxAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page number used to specify which set of results to retrieve.
        /// </summary>
        internal static string Commands_FlowSynxPage {
            get {
                return ResourceManager.GetString("Commands_FlowSynxPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of items or records to include per page.
        /// </summary>
        internal static string Commands_FlowSynxPageSize {
            get {
                return ResourceManager.GetString("Commands_FlowSynxPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display the health status of FlowSynx System.
        /// </summary>
        internal static string Commands_Health_Description {
            get {
                return ResourceManager.GetString("Commands_Health_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning Initialize....
        /// </summary>
        internal static string Commands_Init_BeginningInitialize {
            get {
                return ResourceManager.GetString("Commands_Init_BeginningInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installs and initializes the FlowSynx system for the current user profile..
        /// </summary>
        internal static string Commands_Init_Description {
            get {
                return ResourceManager.GetString("Commands_Init_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The downloaded data may has been corrupted!.
        /// </summary>
        internal static string Commands_Init_DownloadedDataCorrupted {
            get {
                return ResourceManager.GetString("Commands_Init_DownloadedDataCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlowSynx system is downloaded and installed successfully in path &apos;{0}&apos;..
        /// </summary>
        internal static string Commands_Init_FlowSynxSystemDownloadedAndInstalledSuccessfully {
            get {
                return ResourceManager.GetString("Commands_Init_FlowSynxSystemDownloadedAndInstalledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FlowSynx system is already initialized..
        /// </summary>
        internal static string Commands_Init_FlowSynxSystemIsAlreadyInitialized {
            get {
                return ResourceManager.GetString("Commands_Init_FlowSynxSystemIsAlreadyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of the FlowSynx system to install, for example: 1.0.0.
        /// </summary>
        internal static string Commands_Init_FlowSynxVersionOption {
            get {
                return ResourceManager.GetString("Commands_Init_FlowSynxVersionOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting to change the execution mode of FlowSynx..
        /// </summary>
        internal static string Commands_Init_StartChangeExecutionMode {
            get {
                return ResourceManager.GetString("Commands_Init_StartChangeExecutionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start download FlowSynx Console binary.
        /// </summary>
        internal static string Commands_Init_StartDownloadConsoleBinary {
            get {
                return ResourceManager.GetString("Commands_Init_StartDownloadConsoleBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start download FlowSynx system binary.
        /// </summary>
        internal static string Commands_Init_StartDownloadFlowSynxSystemBinary {
            get {
                return ResourceManager.GetString("Commands_Init_StartDownloadFlowSynxSystemBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting extract FlowSynx Console binary.
        /// </summary>
        internal static string Commands_Init_StartExtractingConsoleBinary {
            get {
                return ResourceManager.GetString("Commands_Init_StartExtractingConsoleBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting extract FlowSynx system binary.
        /// </summary>
        internal static string Commands_Init_StartExtractingFlowSynxSystemBinary {
            get {
                return ResourceManager.GetString("Commands_Init_StartExtractingFlowSynxSystemBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start validating FlowSynx Console binary.
        /// </summary>
        internal static string Commands_Init_StartValidatingConsoleBinary {
            get {
                return ResourceManager.GetString("Commands_Init_StartValidatingConsoleBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start validating FlowSynx system binary.
        /// </summary>
        internal static string Commands_Init_StartValidatingFlowSynxSystemBinary {
            get {
                return ResourceManager.GetString("Commands_Init_StartValidatingFlowSynxSystemBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating Console download - Fail!.
        /// </summary>
        internal static string Commands_Init_ValidatingConsoleFailed {
            get {
                return ResourceManager.GetString("Commands_Init_ValidatingConsoleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating download - Fail!.
        /// </summary>
        internal static string Commands_Init_ValidatingFlowSynxSystemFailed {
            get {
                return ResourceManager.GetString("Commands_Init_ValidatingFlowSynxSystemFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Username and Password!.
        /// </summary>
        internal static string Commands_Login_BasicAuthentication_EnterUsernameAndPassword {
            get {
                return ResourceManager.GetString("Commands_Login_BasicAuthentication_EnterUsernameAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in with Basic Authentication successfully..
        /// </summary>
        internal static string Commands_Login_BasicAuthenticationLoggedSuccessfully {
            get {
                return ResourceManager.GetString("Commands_Login_BasicAuthenticationLoggedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login using basic authentication.
        /// </summary>
        internal static string Commands_Login_BasicAuthenticationOption {
            get {
                return ResourceManager.GetString("Commands_Login_BasicAuthenticationOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the password for basic authentication.
        /// </summary>
        internal static string Commands_Login_BasicAuthenticationPasswordOption {
            get {
                return ResourceManager.GetString("Commands_Login_BasicAuthenticationPasswordOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the username for basic authentication.
        /// </summary>
        internal static string Commands_Login_BasicAuthenticationUsernameOption {
            get {
                return ResourceManager.GetString("Commands_Login_BasicAuthenticationUsernameOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter token!.
        /// </summary>
        internal static string Commands_Login_BearerAuthenticationEnterToken {
            get {
                return ResourceManager.GetString("Commands_Login_BearerAuthenticationEnterToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in with Bearer Token successfully..
        /// </summary>
        internal static string Commands_Login_BearerAuthenticationLoggedSuccessfully {
            get {
                return ResourceManager.GetString("Commands_Login_BearerAuthenticationLoggedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login using bearer authentication.
        /// </summary>
        internal static string Commands_Login_BearerAuthenticationOption {
            get {
                return ResourceManager.GetString("Commands_Login_BearerAuthenticationOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the token for bearer authentication.
        /// </summary>
        internal static string Commands_Login_BearerAuthenticationTokenOption {
            get {
                return ResourceManager.GetString("Commands_Login_BearerAuthenticationTokenOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticates the user and establishes a session with the FlowSynx system.
        /// </summary>
        internal static string Commands_Login_Description {
            get {
                return ResourceManager.GetString("Commands_Login_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use no authentication. Sends requests without credentials and overrides any saved login..
        /// </summary>
        internal static string Commands_Login_NoAuthenticationOption {
            get {
                return ResourceManager.GetString("Commands_Login_NoAuthenticationOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify one of the authentication type: --basic, --bearer, or --oauth.
        /// </summary>
        internal static string Commands_Login_SpecifyAuthenticationType {
            get {
                return ResourceManager.GetString("Commands_Login_SpecifyAuthenticationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close authentication session with the FlowSynx system.
        /// </summary>
        internal static string Commands_Logout_Description {
            get {
                return ResourceManager.GetString("Commands_Logout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout successfully..
        /// </summary>
        internal static string Commands_Logout_LogoutSuccessfully {
            get {
                return ResourceManager.GetString("Commands_Logout_LogoutSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get FlowSynx System logs.
        /// </summary>
        internal static string Commands_Logs_Description {
            get {
                return ResourceManager.GetString("Commands_Logs_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the end date from which log entries should be retrieved..
        /// </summary>
        internal static string Commands_Logs_EndDateOption {
            get {
                return ResourceManager.GetString("Commands_Logs_EndDateOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; is already exist!.
        /// </summary>
        internal static string Commands_Logs_ExportToFileIsAlreadyExist {
            get {
                return ResourceManager.GetString("Commands_Logs_ExportToFileIsAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path where the logs data are going to exported.
        /// </summary>
        internal static string Commands_Logs_ExportToOption {
            get {
                return ResourceManager.GetString("Commands_Logs_ExportToOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the start date from which log entries should be retrieved..
        /// </summary>
        internal static string Commands_Logs_FromDateOption {
            get {
                return ResourceManager.GetString("Commands_Logs_FromDateOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The log verbosity to controls the amount of detail emitted for each event that is logged. Valid values are Dbug|Info|Warn|Fail|Crit [default: off].
        /// </summary>
        internal static string Commands_Logs_LogLevelOption {
            get {
                return ResourceManager.GetString("Commands_Logs_LogLevelOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the log message content to be searched.
        /// </summary>
        internal static string Commands_Logs_MessageOption {
            get {
                return ResourceManager.GetString("Commands_Logs_MessageOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting Command-Line output.
        /// </summary>
        internal static string Commands_Output_Format {
            get {
                return ResourceManager.GetString("Commands_Output_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage and display the list and details of plugins supported by the FlowSynx system..
        /// </summary>
        internal static string Commands_Plugins_Description {
            get {
                return ResourceManager.GetString("Commands_Plugins_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get details about plugin.
        /// </summary>
        internal static string Commands_Plugins_DetailsDescription {
            get {
                return ResourceManager.GetString("Commands_Plugins_DetailsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin identity.
        /// </summary>
        internal static string Commands_Plugins_DetailsIdentityOption {
            get {
                return ResourceManager.GetString("Commands_Plugins_DetailsIdentityOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No plugin version was specified; using &apos;{0}&apos;..
        /// </summary>
        internal static string Commands_Plugins_Install_DefaultVersionInfo {
            get {
                return ResourceManager.GetString("Commands_Plugins_Install_DefaultVersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the plugin type should be installed..
        /// </summary>
        internal static string Commands_Plugins_Install_TypeOption {
            get {
                return ResourceManager.GetString("Commands_Plugins_Install_TypeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install plugin.
        /// </summary>
        internal static string Commands_Plugins_InstallDescription {
            get {
                return ResourceManager.GetString("Commands_Plugins_InstallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the new plugin version should be installed..
        /// </summary>
        internal static string Commands_Plugins_NewVersionOption {
            get {
                return ResourceManager.GetString("Commands_Plugins_NewVersionOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the old plugin version should be uninstalled..
        /// </summary>
        internal static string Commands_Plugins_OldVersionOption {
            get {
                return ResourceManager.GetString("Commands_Plugins_OldVersionOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the plugin type should be Uninstalled..
        /// </summary>
        internal static string Commands_Plugins_UnInstall_TypeOption {
            get {
                return ResourceManager.GetString("Commands_Plugins_UnInstall_TypeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall plugin.
        /// </summary>
        internal static string Commands_Plugins_UninstallDescription {
            get {
                return ResourceManager.GetString("Commands_Plugins_UninstallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update plugin.
        /// </summary>
        internal static string Commands_Plugins_UpdateDescription {
            get {
                return ResourceManager.GetString("Commands_Plugins_UpdateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the plugin version to install. Defaults to &apos;latest&apos; when omitted..
        /// </summary>
        internal static string Commands_Plugins_VersionOption {
            get {
                return ResourceManager.GetString("Commands_Plugins_VersionOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flowctl controls the FlowSynx engine.
        /// </summary>
        internal static string Commands_RootDescription {
            get {
                return ResourceManager.GetString("Commands_RootDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run and execute the FlowSynx system under the current user profile.
        /// </summary>
        internal static string Commands_Run_Description {
            get {
                return ResourceManager.GetString("Commands_Run_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FlowSynx system is not installed. Please run the &apos;synx init -h&apos; command for more details..
        /// </summary>
        internal static string Commands_Run_FlowSynxIsNotInstalled {
            get {
                return ResourceManager.GetString("Commands_Run_FlowSynxIsNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop the FlowSynx system and its associated applications running under the current user profile..
        /// </summary>
        internal static string Commands_Stop_Description {
            get {
                return ResourceManager.GetString("Commands_Stop_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FlowSynx Console has been successfully stopped..
        /// </summary>
        internal static string Commands_Stop_StopConsoleSuccessfully {
            get {
                return ResourceManager.GetString("Commands_Stop_StopConsoleSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FlowSynx system has been successfully stopped..
        /// </summary>
        internal static string Commands_Stop_StopFlowSynxSuccessfully {
            get {
                return ResourceManager.GetString("Commands_Stop_StopFlowSynxSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop the FlowSynx Console running under the current user profile..
        /// </summary>
        internal static string Commands_StopConsole_Description {
            get {
                return ResourceManager.GetString("Commands_StopConsole_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning uninstalling....
        /// </summary>
        internal static string Commands_Uninstall_BeginningUninstalling {
            get {
                return ResourceManager.GetString("Commands_Uninstall_BeginningUninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FlowSynx Console is currently running. Please stop it before attempting to uninstall it..
        /// </summary>
        internal static string Commands_Uninstall_ConsoleIsRunning {
            get {
                return ResourceManager.GetString("Commands_Uninstall_ConsoleIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling the FlowSynx System from the current user&apos;s profile and local machine environment.
        /// </summary>
        internal static string Commands_Uninstall_Description {
            get {
                return ResourceManager.GetString("Commands_Uninstall_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FlowSynx system is currently running. Please stop it before attempting to uninstall it..
        /// </summary>
        internal static string Commands_Uninstall_FlowSynxSystemIsRunning {
            get {
                return ResourceManager.GetString("Commands_Uninstall_FlowSynxSystemIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forcefully terminates the FlowSynx system processes if it is currently running..
        /// </summary>
        internal static string Commands_Uninstall_ForceTerminateOption {
            get {
                return ResourceManager.GetString("Commands_Uninstall_ForceTerminateOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FlowSynx system has been successfully stopped..
        /// </summary>
        internal static string Commands_Uninstall_StopSuccessfully {
            get {
                return ResourceManager.GetString("Commands_Uninstall_StopSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FlowSynx system has been uninstalled successfully..
        /// </summary>
        internal static string Commands_Uninstall_UninstalledSuccessfully {
            get {
                return ResourceManager.GetString("Commands_Uninstall_UninstalledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for FlowSynx updates....
        /// </summary>
        internal static string Commands_Update_CheckingForFlowSynxSystemUpdates {
            get {
                return ResourceManager.GetString("Commands_Update_CheckingForFlowSynxSystemUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates the FlowSynx system.
        /// </summary>
        internal static string Commands_Update_Description {
            get {
                return ResourceManager.GetString("Commands_Update_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The downloaded data may has been corrupted!.
        /// </summary>
        internal static string Commands_Update_DownloadedDataCorrupted {
            get {
                return ResourceManager.GetString("Commands_Update_DownloadedDataCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FlowSynx system is currently running. Please stop it before attempting to update it..
        /// </summary>
        internal static string Commands_Update_FlowSynxSystemIsRunning {
            get {
                return ResourceManager.GetString("Commands_Update_FlowSynxSystemIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current version of FlowSynx system is up to date.
        /// </summary>
        internal static string Commands_Update_FlowSynxSystemIsUpToDate {
            get {
                return ResourceManager.GetString("Commands_Update_FlowSynxSystemIsUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of the FlowSynx system to update, for example: 1.0.0.
        /// </summary>
        internal static string Commands_Update_FlowSynxVersionOption {
            get {
                return ResourceManager.GetString("Commands_Update_FlowSynxVersionOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forcefully terminates the FlowSynx system processes if it is currently running..
        /// </summary>
        internal static string Commands_Update_ForceTerminateOption {
            get {
                return ResourceManager.GetString("Commands_Update_ForceTerminateOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start download FlowSynx system binary.
        /// </summary>
        internal static string Commands_Update_StartDownloadFlowSynxSystemBinary {
            get {
                return ResourceManager.GetString("Commands_Update_StartDownloadFlowSynxSystemBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting extract FlowSynx system binary.
        /// </summary>
        internal static string Commands_Update_StartExtractingFlowSynxSystemBinary {
            get {
                return ResourceManager.GetString("Commands_Update_StartExtractingFlowSynxSystemBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start validating FlowSynx system binary.
        /// </summary>
        internal static string Commands_Update_StartValidatingFlowSynxSystemBinary {
            get {
                return ResourceManager.GetString("Commands_Update_StartValidatingFlowSynxSystemBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating FlowSynx download - Fail!.
        /// </summary>
        internal static string Commands_Update_ValidatingFlowSynxSystemFailed {
            get {
                return ResourceManager.GetString("Commands_Update_ValidatingFlowSynxSystemFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the FlowSynx system version and CLI version..
        /// </summary>
        internal static string Commands_Version_Description {
            get {
                return ResourceManager.GetString("Commands_Version_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not initialized.
        /// </summary>
        internal static string Commands_Version_NotInitialized {
            get {
                return ResourceManager.GetString("Commands_Version_NotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get list of pending approvals about workflow execution.
        /// </summary>
        internal static string Commands_Workflow_Execution_ApprovalsDescription {
            get {
                return ResourceManager.GetString("Commands_Workflow_Execution_ApprovalsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve the pending task in executed workflow.
        /// </summary>
        internal static string Commands_Workflow_Execution_ApprovePendingTaskDescription {
            get {
                return ResourceManager.GetString("Commands_Workflow_Execution_ApprovePendingTaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel the executed workflow.
        /// </summary>
        internal static string Commands_Workflow_Execution_CancelDescription {
            get {
                return ResourceManager.GetString("Commands_Workflow_Execution_CancelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get details about workflow execution.
        /// </summary>
        internal static string Commands_Workflow_Execution_DetailsDescription {
            get {
                return ResourceManager.GetString("Commands_Workflow_Execution_DetailsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get logs about workflow execution.
        /// </summary>
        internal static string Commands_Workflow_Execution_LogsDescription {
            get {
                return ResourceManager.GetString("Commands_Workflow_Execution_LogsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject the pending task in executed workflow.
        /// </summary>
        internal static string Commands_Workflow_Execution_RejectPendingTaskDescription {
            get {
                return ResourceManager.GetString("Commands_Workflow_Execution_RejectPendingTaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get details about workflow trigger.
        /// </summary>
        internal static string Commands_Workflow_Triggers_DetailsDescription {
            get {
                return ResourceManager.GetString("Commands_Workflow_Triggers_DetailsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A JSON-serialized definition data.
        /// </summary>
        internal static string Commands_Workflows_Add_DefinitionData {
            get {
                return ResourceManager.GetString("Commands_Workflows_Add_DefinitionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file containing JSON-serialized definition data.
        /// </summary>
        internal static string Commands_Workflows_Add_DefinitionDataFile {
            get {
                return ResourceManager.GetString("Commands_Workflows_Add_DefinitionDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add workflow.
        /// </summary>
        internal static string Commands_Workflows_AddDescription {
            get {
                return ResourceManager.GetString("Commands_Workflows_AddDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete workflow.
        /// </summary>
        internal static string Commands_Workflows_DeleteDescription {
            get {
                return ResourceManager.GetString("Commands_Workflows_DeleteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow identity.
        /// </summary>
        internal static string Commands_Workflows_DeleteIdentityOption {
            get {
                return ResourceManager.GetString("Commands_Workflows_DeleteIdentityOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage and display the list and details of workflows..
        /// </summary>
        internal static string Commands_Workflows_Description {
            get {
                return ResourceManager.GetString("Commands_Workflows_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get details about workflow.
        /// </summary>
        internal static string Commands_Workflows_DetailsDescription {
            get {
                return ResourceManager.GetString("Commands_Workflows_DetailsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow identity.
        /// </summary>
        internal static string Commands_Workflows_DetailsIdentityOption {
            get {
                return ResourceManager.GetString("Commands_Workflows_DetailsIdentityOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute workflow.
        /// </summary>
        internal static string Commands_Workflows_ExecuteDescription {
            get {
                return ResourceManager.GetString("Commands_Workflows_ExecuteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow identity.
        /// </summary>
        internal static string Commands_Workflows_ExecuteIdentityOption {
            get {
                return ResourceManager.GetString("Commands_Workflows_ExecuteIdentityOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution approval identity.
        /// </summary>
        internal static string Commands_Workflows_Execution_ApprovalIdentityOption {
            get {
                return ResourceManager.GetString("Commands_Workflows_Execution_ApprovalIdentityOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution identity.
        /// </summary>
        internal static string Commands_Workflows_Execution_IdentityOption {
            get {
                return ResourceManager.GetString("Commands_Workflows_Execution_IdentityOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow identity.
        /// </summary>
        internal static string Commands_Workflows_Executions_IdentityOption {
            get {
                return ResourceManager.GetString("Commands_Workflows_Executions_IdentityOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow executions list.
        /// </summary>
        internal static string Commands_Workflows_ExecutionsListDescription {
            get {
                return ResourceManager.GetString("Commands_Workflows_ExecutionsListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow identity.
        /// </summary>
        internal static string Commands_Workflows_IdentityOption {
            get {
                return ResourceManager.GetString("Commands_Workflows_IdentityOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A JSON-serialized definition data.
        /// </summary>
        internal static string Commands_Workflows_Triggers_Add_DefinitionData {
            get {
                return ResourceManager.GetString("Commands_Workflows_Triggers_Add_DefinitionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file containing JSON-serialized definition data.
        /// </summary>
        internal static string Commands_Workflows_Triggers_Add_DefinitionDataFile {
            get {
                return ResourceManager.GetString("Commands_Workflows_Triggers_Add_DefinitionDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add trigger for a workflow.
        /// </summary>
        internal static string Commands_Workflows_Triggers_AddDescription {
            get {
                return ResourceManager.GetString("Commands_Workflows_Triggers_AddDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete workflow trigger.
        /// </summary>
        internal static string Commands_Workflows_Triggers_DeleteDescription {
            get {
                return ResourceManager.GetString("Commands_Workflows_Triggers_DeleteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger identity.
        /// </summary>
        internal static string Commands_Workflows_Triggers_IdentityOption {
            get {
                return ResourceManager.GetString("Commands_Workflows_Triggers_IdentityOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A JSON-serialized definition data.
        /// </summary>
        internal static string Commands_Workflows_Triggers_Update_DefinitionData {
            get {
                return ResourceManager.GetString("Commands_Workflows_Triggers_Update_DefinitionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file containing JSON-serialized definition data.
        /// </summary>
        internal static string Commands_Workflows_Triggers_Update_DefinitionDataFile {
            get {
                return ResourceManager.GetString("Commands_Workflows_Triggers_Update_DefinitionDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow triggers list.
        /// </summary>
        internal static string Commands_Workflows_TriggersListDescription {
            get {
                return ResourceManager.GetString("Commands_Workflows_TriggersListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A JSON-serialized definition data.
        /// </summary>
        internal static string Commands_Workflows_Update_DefinitionData {
            get {
                return ResourceManager.GetString("Commands_Workflows_Update_DefinitionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file containing JSON-serialized definition data.
        /// </summary>
        internal static string Commands_Workflows_Update_DefinitionDataFile {
            get {
                return ResourceManager.GetString("Commands_Workflows_Update_DefinitionDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update workflow.
        /// </summary>
        internal static string Commands_Workflows_UpdateDescription {
            get {
                return ResourceManager.GetString("Commands_Workflows_UpdateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow identity.
        /// </summary>
        internal static string Commands_Workflows_UpdateIdentityOption {
            get {
                return ResourceManager.GetString("Commands_Workflows_UpdateIdentityOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data conversion encountered an error. The system couldn&apos;t process the data format..
        /// </summary>
        internal static string ConsoleLogger_DataConversionError {
            get {
                return ResourceManager.GetString("ConsoleLogger_DataConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong happen during execute the application.
        /// </summary>
        internal static string Error_During_Initializing_Application {
            get {
                return ResourceManager.GetString("Error_During_Initializing_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The base location could not be found..
        /// </summary>
        internal static string LocationService_ErrorDuringGettingRootLocation {
            get {
                return ResourceManager.GetString("LocationService_ErrorDuringGettingRootLocation", resourceCulture);
            }
        }
    }
}
